version: '3.7'

services:

    node:
        container_name: 'thiagoalves.dev'
        build: .docker/node
        volumes:
            - '.:/var/www/html/thiagoalves.dev'
        ports:
            - '3000:3000'
        command: >
            bash -c "yarn install && yarn dev"