version: '3'

services:
  php:
    build: .docker/php
    container_name: 'Mastercode-Blog-Application'
    volumes:
      - .:/var/www/html/blog
    ports:
      - 3000:3000
    command: >
      bash -c "composer update && yarn && yarn watch"

volumes:
  npm-cache:
