/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  safelist: [
    'bg-gray-800',
    'text-white',
    'p-4',
    'container',
    'mx-auto',
    'flex',
    'justify-between',
    'items-center',
    'text-xl',
    'font-bold',
    'space-x-4',
    'hover:text-gray-300',
    'flex-grow',
    'px-4',
    'py-8',
    'text-center',
    'text-4xl',
    'mb-8',
    'text-lg',
    'mb-6',
    'mb-4',
    'text-6xl',
    'text-red-500',
    'text-2xl',
    'bg-blue-500',
    'hover:bg-blue-700',
    'py-2',
    'px-4',
    'rounded',
    'flex-col',
    'min-h-screen'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
